### PR TITLE
Remove feature that exports client certs and keys to facts

### LINKED ISSUE #322: Fact openvpn exposes private keys
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: n/a
- Ruby: n/a
- Distribution: n/a
- Module version: 7.1.0+

## How to reproduce (e.g Puppet code you use)

Any openvpn configuration with a least one client will do.

## What are you seeing

With d0fd9f31861c3ff7692a97ed42f88b24e9bba984 a fact has been added to the base module that unconditionally exports private keys as facts. I think this is a security issue.

IMHO facts should not contain sensitive data such as passwords and keys, as they might be viewed on dashboards and the like. Couldn't the problem d0fd9f31861c3ff7692a97ed42f88b24e9bba984 tries to address be solved with exported resources only?

If a maintainer agrees with my opinion, I will try to come up with an alternative implementation that would drop sensitive data from the fact (or get rid of it altogether). Otherwise feel free to close the issue.

### PR DESCRIPTION
**Pull request by TheBigLee**
#### Pull Request (PR) description
Exporting private keys via facts is unsafe as facts should not contain
sensitive information, as they might be accessible from undesired
systems (eg. dashboards)

This feature has been added in commit voxpupuli@d0fd9f3 as a result of
voxpupuli/puppet-openvpn#231

This commit reverts the changes and removes the added feature for
security reasons.
#### This Pull Request (PR) fixes the following issues
Fixes #322

### CODE REVIEW

**Comment by davidgubler** [comment]
I can't really judge if this will break anything, but if it still works I guess it's ok like this.

**Comment by TheBigLee** [comment]
> I can't really judge if this will break anything, but if it still works I guess it's ok like this.

It won't break anything for us, as we don't use the feature. (tested in vagrant)

**Review by davidgubler — APPROVED** [review]
I can't really judge if this will break anything, but if it still works I guess it's ok like this.

**Comment by vanElden** [comment]
lgtm

**Pull request merged**
